# ????
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    username: root
  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
  mail:
    host: smtp.qq.com
    port: 587
    username: 1315077391@qq.com
    password: kwjgpzhutlyshjab
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys_drug?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: thr010410
    # 数据库连接池
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间
      max-lifetime: 1800000
      # 连接最大超时时间
      connection-timeout: 30000
      # 测试语句
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml


# ?? sql
logging:
  level:
    com.harlon.drugmanagement.dao: debug
# 腾讯云短信相关配置
Sms:
  secretId: AKIDgBQO7ZkeHejX4KK3VszpOffOq0uYv0oM
  secretKey: IJ3X9YgZCaiaDahYAXeV7TaR2NSIsDI7
  appid: 1400626380
  sign: 田浩然前端技术分享
  templateID: 1290007

oss:
  endpoin: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tM24V9zvWMxvjJYbyC5
  accessKeySecret: S0KCuBBZaRrc3qMgSUa4UCgTCSCICf
  bucketName: cloudcenter

